name: Build & Release Signed APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Assembly (APK)
        run: ./gradlew assemble --stacktrace

      - name: Sign APK with Secrets
        uses: r3d-buck/gradle-build-action@v1
        continue-on-error: true

      - name: Sign Android APK
        uses: r2da/android-sign-apk@v1.0.0
        id: sign_app
        with:
          apkPath: 'app/build/outputs/apk/release/*.apk'
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          keystoreBase64: ${{ secrets.KEYSTORE_FILE_BASE64 }}

      - name: Upload Signed Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Yaraan-Release-APK
          path: app/build/outputs/apk/**/*.apk
